name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "opened", "edited", "reopened", "synchronize", "ready_for_review" ]

permission: 
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies with Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
    - run: npm ci
    - run: npm run lint